### PR TITLE
Updates dependencies

### PR DESCRIPTION
**Pull request by estevaoam**
To work with the newest version of Rspec.

### CODE REVIEW

**Comment by twe4ked** [comment]
Thanks for the PR. Wouldn't the `>=` versions work with the versions you're suggesting though?

**Comment by estevaoam** [comment]
I've tried using it as it was and even with `bundle update`, it didn't update to the right version. :confused:

**Comment by twe4ked** [comment]
I've had trouble getting gems to update in the past and resorted to editing the Gemfile.lock.

**Comment by san983** [comment]
:+1: for this PR

**Comment by pboling** [comment]
@estevaoam you need to specify the version constraints you want for your app within your app's own Gemfile.  Don't rely on this gem to pull in the gems you want if your app relies on them directly.  The `>=` here is fine if it is accurately representing the supported versions.

CC @twe4ked

**Comment by twe4ked** [comment]
Thanks @pboling, I'd forgotten about this.

**Pull request closed without merging**
